<Project Sdk="Uno.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\src\CConner100.RichEditBoxLite\CConner100.RichEditBoxLite.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <TargetFrameworks>net10.0-android;net10.0-ios;net10.0-browserwasm;net10.0-desktop;net10.0</TargetFrameworks>

    <OutputType>Exe</OutputType>
    <UnoSingleProject>true</UnoSingleProject>

    <!-- Display name -->
    <ApplicationTitle>RichEditBoxLite.TestApp</ApplicationTitle>
    <!-- App Identifier -->
    <ApplicationId>com.cconner100.richeditboxlite.testapp</ApplicationId>
    <!-- Versions -->
    <ApplicationDisplayVersion>1.0</ApplicationDisplayVersion>
    <ApplicationVersion>1</ApplicationVersion>
    <!-- Package Publisher -->
    <ApplicationPublisher>RichEditBoxLite.TestApp</ApplicationPublisher>
    <!-- Package Description -->
    <Description>RichEditBoxLite.TestApp powered by Uno Platform.</Description>

    <!--
      UnoFeatures are used to quickly add and manage features enabled for your app.
      https://aka.platform.uno/singleproject-features
    -->
    <UnoFeatures>
      SkiaRenderer;
    </UnoFeatures>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Debug' or '$(IsUiAutomationMappingEnabled)'=='True'">
    <IsUiAutomationMappingEnabled>True</IsUiAutomationMappingEnabled>
    <DefineConstants>$(DefineConstants);USE_UITESTS</DefineConstants>
  </PropertyGroup>

</Project>
